format = """
$hostname\
[](fg:host_bg_color bg:dir_bg_color)\
$directory\
[](fg:dir_bg_color bg:vcs_bg_color)\
$git_branch\
$git_status\
$hg_branch\
[](fg:vcs_bg_color bg:code_bg_color)\
$buf\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$nix_shell\
$python\
$rust\
$scala\
[](fg:code_bg_color bg:tool_bg_color)\
$kubernetes\
$container\
$docker_context\
[](fg:tool_bg_color bg:character_bg_color)\
$cmd_duration\
\
\n$character


"""
palette = "frost"

# Nord Frost
[palettes.frost]
dir_bg_color = '#5E81AC'
vcs_bg_color = '#81A1C1'
code_bg_color = '#88C0D0'
tool_bg_color = '#8FBCBB'
text_color = '#2E3440'
character_bg_color = '#D8DEE9'
character_text_color = '#2E3440'
character_text_error_color = '#BF616A' 
host_bg_color = '#4C566A'

[buf]
symbol = "󰿘 "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'


#[character]
#success_symbol = "[](fg:character_bg_color bg:character_bg_color)[](fg:character_bg_color)"
#error_symbol = "[](fg:character_bg_color bg:character_text_error_color)[](fg:character_text_error_color)"

[cmd_duration]
min_time = 0
style = "bg:character_bg_color fg:character_text_color"
format = '[ $duration ]($style)'

[directory]
style = "bg:dir_bg_color fg:text_color"
format = "[ $path $read_only ]($style)"
home_symbol = "󰟒"
# fish_style does not work if substitutions are on
#fish_style_pwd_dir_length = 2
truncation_symbol = "󰦩 "
read_only = "󰌾 "
#truncate_to_repo = false

[directory.substitutions]
"/" = "  "

[c]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[docker_context]
disabled = false
symbol = " "
style = "bg:tool_bg_color fg:text_color"
format = '[ $symbol $context ]($style) $path'

[kubernetes]
symbol = "󱃾 "
disabled = false
format = '[ $symbol $cluster ]($style)'
style = "bg:tool_bg_color fg:text_color"

[elixir]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "󰊢"
style = "bg:vcs_bg_color fg:text_color"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:vcs_bg_color fg:text_color"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[hostname]
ssh_only = false
style = "bg:host_bg_color fg:text_color"
format = "[ $hostname ]($style)" 

[java]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[hg_branch]
symbol = ""
style = "bg:vcs_bg_color fg:text_color"
format = '[ $symbol $branch ]($style)'
disabled = false

[python]
symbol = " " 
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:code_bg_color fg:text_color"
format = '[ $symbol ($version) ]($style)'
